[workspace]
authors = ["alperNB <alper@neuralbridge.ai>"]
channels = ["conda-forge"]
name = "llm"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
server = "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

[dependencies]
python = ">=3.14.0,<3.15"

[pypi-dependencies]
fastapi = ">=0.121.2, <0.122"
uvicorn = ">=0.38.0, <0.39"
openai = ">=2.8.1, <3"
pydantic = ">=2.12.4, <3"
python-dotenv = ">=1.2.1, <2"
